// Set of string literals to be used in redux actions and reducers
// These are preferred due to lower risk of misspelling an action

const constants = {
    ADD_TASK: "ADD_TASK",
    SET_TASKS: "SET_TASKS",
    EDIT_TASK: "EDIT_TASK",
    DELETE_TASK: "DELETE_TASK",
    TASK_ENTER_EDIT_MODE: "TASK_ENTER_EDIT_MODE",
    TASK_EXIT_EDIT_MODE: "TASK_EXIT_EDIT_MODE",
    ADD_BUCKETLIST: "ADD_BUCKETLIST",
    SET_BUCKETLISTS: "SET_BUCKETLISTS",
    APPEND_BUCKETLISTS: "APPEND_BUCKETLISTS",
    EDIT_BUCKETIST: "EDIT_BUCKETLIST",
    DELETE_BUCKETLIST: "DELETE_BUCKETLIST",
    BUCKET_ENTER_EDIT_MODE: "BUCKET_ENTER_EDIT_MODE",
    BUCKET_EXIT_EDIT_MODE: "BUCKET_EXIT_EDIT_MODE",
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    DELETE_ALL_BUCKETLISTS: "DELETE_ALL_BUCKETLISTS",
    ADD_SEARCHED_BUCKETLISTS: "ADD_SEARCHED_BUCKETLISTS",
    DELETE_ALL_SEARCHED_BUCKETLISTS: "DELETE_ALL_SEARCHED_BUCKETLISTS",
    ADD_NOTIFICATION: "ADD_NOTIFICATION",
    CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS",
    HAS_NEXT_PAGE: "HAS_NEXT_PAGE",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    RESET_PAGE_COUNTER: "RESET_PAGE_COUNTER"
};

export default constants